<?xml version="1.0" ?>
<robot name="Anton" xmlns:xacro="https://www.ros.org/wiki/xacro" >
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>false</alwaysOn>
      <legacyMode>false</legacyMode>
      <updateRate>20</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation> ${wheel_separation} 
      </wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}
      </wheelDiameter>
      <torque>20</torque>
      <commandTopic>
        /ai_rover_remastered/base_controller/cmd_vel
      </commandTopic>
      <odometryTopic> 
        /ai_rover_remastered/base_controller/odom
      </odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>
  </gazebo> 
</robot>