<?xml version="1.0"?>
<robot name="Anton" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="base_width" value="0.16"/>
  <xacro:property name="base_length" value="0.16"/>
  <xacro:property name="wheel_radius" value="0.035"/>
  
  <xacro:property name="base_wheel_gap" value="0.007"/>
  <xacro:property name="wheel_separation" value="0.15"/>
  <xacro:property name="wheel_joint_offset" value="0.02"/>

  <xacro:property name="caster_wheel_radius" value="${wheel_radius/2}"/>
  <xacro:property name="caster_wheel_mass" value="0.001"/>
  <xacro:property name="caster_wheel_joint_offset" value="-0.052"/>
</robot>
