<?xml version="1.0"?>

<robot name="Anton" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="camera_size_x" value="0.015"/>
    <xacro:property name="camera_size_y" value="0.13"/>
    <xacro:property name="camera_size_z" value="0.022"/>
    <xacro:property name="camera_origin_x" value="${base_length/2}"/>
    <xacro:property name="camera_origin_y" value="0"/>
    <xacro:property name="camera_origin_z" value="${base_height/2}"/>
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_size_x} ${camera_size_y} ${camera_size_z}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_size_x} ${camera_size_y} ${camera_size_z}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="0.035" w="${camera_size_x}" h="${camera_size_y}" d="${camera_size_z}"/>
    </link>
    <joint name="camera_joint" type="fixed">
        <origin xyz="${camera_origin_x} ${camera_origin_y} ${camera_origin_z}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="camera_link" />
    </joint>
    <link name="camera_depth_frame"/>
    <joint name="camera_depth_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera_link"/>
        <child link="camera_depth_frame"/>
    </joint>
</robot>
