<?xml version="1.0"?>
<robot name="Anton" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="caster_wheel_radius" value="${wheel_radius/2}"/>
  <xacro:property name="caster_wheel_mass" value="0.001"/>
  <xacro:property name="caster_wheel_joint_offset" value="${base_length/3}"/>
</robot>